# Generated by Django 4.0.1 on 2022-02-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fully',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=255)),
            ],
        ),
    ]
