# Generated by Django 4.0.1 on 2022-02-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_fully'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fully',
        ),
    ]
