# Generated by Django 4.0.1 on 2022-02-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Me',
        ),
    ]
