# Generated by Django 4.0.1 on 2022-02-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narhlar', models.CharField(max_length=255)),
            ],
        ),
    ]
