# Generated by Django 4.0.1 on 2022-02-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.CharField(max_length=255)),
            ],
        ),
    ]
