# Generated by Django 4.0.1 on 2022-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_startnow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_haqimizda', models.CharField(max_length=255)),
            ],
        ),
    ]
