# Generated by Django 4.0.1 on 2022-02-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_haqida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmat_korsatish', models.CharField(max_length=255)),
            ],
        ),
    ]
