# Generated by Django 4.0.1 on 2022-02-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_servis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servis',
            old_name='hizmat_korsatish',
            new_name='hizmat',
        ),
    ]
