# Generated by Django 4.0.1 on 2022-02-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_rename_hizmat_korsatish_servis_hizmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oson', models.CharField(max_length=255)),
            ],
        ),
    ]
