# Generated by Django 4.0.1 on 2022-02-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_simple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuchli', models.CharField(max_length=255)),
            ],
        ),
    ]
