# Generated by Django 4.0.1 on 2022-02-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_powerful_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='haqida',
            name='tekst',
            field=models.CharField(default=2, max_length=355),
            preserve_default=False,
        ),
    ]
