# Generated by Django 4.0.1 on 2022-02-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_servis_tekst1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muvaffaqiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuksalishimiz_siri', models.CharField(max_length=355)),
                ('tekst2', models.CharField(max_length=355)),
            ],
        ),
    ]
