# Generated by Django 4.0.1 on 2022-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Great',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zor', models.CharField(max_length=355)),
                ('tekst3', models.CharField(max_length=500)),
            ],
        ),
    ]
