# Generated by Django 4.0.1 on 2022-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_great'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alo', models.CharField(max_length=355)),
                ('tekst4', models.CharField(max_length=500)),
            ],
        ),
    ]
