# Generated by Django 4.0.1 on 2022-02-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_best'),
    ]

    operations = [
        migrations.RenameField(
            model_name='best',
            old_name='tekst4',
            new_name='tab',
        ),
    ]
