# Generated by Django 4.0.1 on 2022-02-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oqish', models.CharField(max_length=355)),
                ('talim_olish', models.CharField(max_length=500)),
            ],
        ),
    ]
