# Generated by Django 4.0.1 on 2022-06-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_contact1_telegram_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle_1', models.CharField(max_length=255)),
                ('text_1', models.TextField()),
                ('tittle_2', models.CharField(max_length=255)),
                ('text_2', models.TextField()),
                ('tittle_3', models.CharField(max_length=255)),
                ('text_3', models.TextField()),
                ('image', models.ImageField(upload_to='Wallet/')),
            ],
        ),
    ]
