# Generated by Django 4.0.1 on 2022-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_remove_wallet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
