# Generated by Django 4.0.1 on 2022-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0043_realclientsimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
