# Generated by Django 4.0.1 on 2022-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0045_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='button',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
