# Generated by Django 4.0.5 on 2022-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0046_prices_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=255)),
                ('text_2', models.TextField()),
                ('image', models.ImageField(upload_to='Comanda/')),
                ('fb_icon', models.CharField(max_length=255)),
                ('tw_icon', models.CharField(max_length=255)),
                ('linkedIn_icon', models.CharField(max_length=255)),
                ('inst_icon', models.CharField(max_length=255)),
            ],
        ),
    ]
