# Generated by Django 4.0.5 on 2022-06-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0047_comanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text_2', models.TextField()),
                ('image', models.ImageField(upload_to='Comanda/')),
                ('fb_icon', models.CharField(max_length=255)),
                ('tw_icon', models.CharField(max_length=255)),
                ('linkedIn_icon', models.CharField(max_length=255)),
                ('inst_icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='fb_icon',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='inst_icon',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='linkedIn_icon',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='text_2',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='tw_icon',
        ),
    ]
