# Generated by Django 4.0.5 on 2022-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0048_comandainfo_remove_comanda_fb_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
