# Generated by Django 4.0.5 on 2022-06-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0049_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=355)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
